



DATABASE_URL=postgresql://neondb_owner:npg_1vIqHE4VAWSk@ep-cold-feather-a1iv6pcd-pooler.ap-southeast-1.aws.neon.tech/neondb?sslmode=require&channel_binding=require

# 複製成 .streamlit/secrets.toml（本機用；Cloud 另外在 Secrets 介面填）
# 本機 Docker 版（開發用；二擇一）
# DATABASE_URL = "postgresql+psycopg2://postgres:postgres@localhost:5432/mydb"
# 雲端 Neon / Supabase（部署用；二擇一）

